### ISSUE TITLE
wcomponent_examples of list components with cachable options do not generate data

### ISSUE THREAD

**Issue by marksreeves** [OpenBorders/wcomponents#24]
The wcomponent_examples for all components which use cacheable datalists are currently not outputting any options.

Steps to recreate: 

1. run wcomponents_examples_lde
2. navigate to example Form controls > dropdown
3. find the dropdown labelled "Drop-down with cached data from a look up table"

We expect to see options in the dropdown. There are none. Investigation of the XML sent to the client shows that the component does not have any options at all. It appears that ExampleLookupTable may be the culprit.

**Comment by ricksbrown** [comment]
Fixed in PR #33
